# Generated by Django 5.0.2 on 2024-02-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('date_fs', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Localisation',
            fields=[
                ('id_local', models.SlugField(max_length=9, primary_key=True, serialize=False)),
                ('code_region', models.IntegerField()),
                ('code_depart', models.CharField(max_length=4)),
                ('libelle_region', models.CharField(max_length=4)),
                ('libelle_depart', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='D_Type',
            fields=[
                ('type_vac', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='F_Vaccin',
            fields=[
                ('id_vac', models.SlugField(primary_key=True, serialize=False)),
                ('nb_ucd', models.PositiveIntegerField()),
                ('nb_doses', models.PositiveIntegerField()),
                ('date_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_date')),
                ('local_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_localisation')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_type')),
            ],
        ),
    ]
