# Generated by Django 5.0.2 on 2024-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_d_localisation_code_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_vaccin',
            name='nb_doses',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='f_vaccin',
            name='nb_ucd',
            field=models.FloatField(),
        ),
    ]
