# Generated by Django 5.0.2 on 2024-02-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.CharField(max_length=255)),
                ('libelle_region', models.CharField(max_length=255)),
                ('code_depart', models.CharField(max_length=255)),
                ('libelle_depart', models.CharField(max_length=255)),
                ('date_fs', models.CharField(max_length=255)),
                ('type_vac', models.CharField(max_length=255)),
                ('nb_ucd', models.CharField(max_length=255)),
                ('nb_doses', models.CharField(max_length=255)),
            ],
        ),
    ]
