# Generated by Django 5.0.2 on 2024-02-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='code_depart',
            new_name='code_departement',
        ),
        migrations.RenameField(
            model_name='vaccination',
            old_name='date_fs',
            new_name='date_fin_semaine',
        ),
        migrations.RenameField(
            model_name='vaccination',
            old_name='libelle_depart',
            new_name='libelle_departement',
        ),
        migrations.RenameField(
            model_name='vaccination',
            old_name='type_vac',
            new_name='type_de_vaccin',
        ),
    ]
